import Head from 'next/head';
import { Geist, Geist_Mono } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Cards from '@/components/Cards';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export async function getServerSideProps() {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000';
  const res = await fetch(`${baseUrl}/api/cards`);
  const data = await res.json();

  return {
    props: {
      initialCards: data,
    },
  };
}

export default function Home({ initialCards = [] }) {
  return (
    <>
      <Head>
        <title>CSS BATTLE VAULT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.mainContainer}>
          <Cards initialCards={initialCards} />
        </main>
      </div>
    </>
  );
}
